spring:
  application:
    name: delivery-service
  datasource:
    url: jdbc:postgresql://localhost:5432/delivery_db
    username: postgres
    password: admin
  flyway:
    enabled: true
    baseline-on-migrate: true
server:
  port: 8085

