services:
  config-server:
    build:
      context: ./${BACKEND_PATH}/${CONFIG_SERVER_SUB_PATH}
      dockerfile: Dockerfile
    container_name: food-delivery-config-server
    ports:
      - "${CONFIG_SERVER_PORT}:${CONFIG_SERVER_PORT}"
    env_file:
      - .env.infra
      - .env.app
      - .env.backend.development
    volumes:
      - ${CONFIG_REPO_PATH}:/app/config-repo
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:${CONFIG_SERVER_PORT}/actuator/health" ]
      interval: 5s
      timeout: 3s
      retries: 5
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - food-delivery-network

  eureka-server:
    build:
      context: ./${BACKEND_PATH}/${EUREKA_SERVER_SUB_PATH}
      dockerfile: Dockerfile
    container_name: food-delivery-eureka-server
    ports:
      - "${EUREKA_SERVER_PORT}:${EUREKA_SERVER_PORT}"
    env_file:
      - .env.infra
      - .env.app
      - .env.backend.development
    depends_on:
      config-server:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:${EUREKA_SERVER_PORT}/actuator/health" ]
      interval: 5s
      timeout: 3s
      retries: 5
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - food-delivery-network
  
  api-gateway:
    build:
      context: ./${BACKEND_PATH}/${API_GATEWAY_SUB_PATH}
      dockerfile: Dockerfile
    container_name: food-delivery-api-gateway
    ports:
      - "${API_GATEWAY_PORT}:${API_GATEWAY_PORT}"
    env_file:
      - .env.infra
      - .env.app
      - .env.backend.development
    depends_on:
      eureka-server:
        condition: service_healthy
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - food-delivery-network

  identity-service:
    build:
      context: ./${BACKEND_PATH}/${IDENTITY_SERVICE_SUB_PATH}
      dockerfile: Dockerfile
    container_name: food-delivery-identity-service
    ports:
      - "${IDENTITY_SERVICE_PORT}:${IDENTITY_SERVICE_PORT}"
    env_file:
      - .env.infra
      - .env.app
      - .env.backend.development
    depends_on:
      eureka-server:
        condition: service_healthy
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - food-delivery-network

  delivery-service:
    build:
      context: ./${BACKEND_PATH}/${DELIVERY_SERVICE_SUB_PATH}
      dockerfile: Dockerfile
    container_name: food-delivery-delivery-service
    ports:
      - "${DELIVERY_SERVICE_PORT}:${DELIVERY_SERVICE_PORT}"
    env_file:
      - .env.infra
      - .env.app
      - .env.backend.development
    depends_on:
      eureka-server:
        condition: service_healthy
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - food-delivery-network

networks:
  food-delivery-network:
    external: true
    name: food-delivery-network