server:
  port: ${DELIVERY_SERVICE_PORT:8086}

spring:
  datasource:
    url: ${DELIVERY_DB_URL:jdbc:postgresql://localhost:5432/delivery_db}
    username: ${DELIVERY_DB_USERNAME:postgres}
    password: ${DELIVERY_DB_PASSWORD:admin}
  flyway:
    enabled: ${DELIVERY_FLYWAY_ENABLED:true}
    baseline-on-migrate: true
  kafka:
    bootstrap-servers: ${KAFKA_SERVERS:localhost:9092}
    consumer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.trusted.packages: "mss301.se1911.group.assignment.deliveryservice.infrastructure.messaging.kafka.event"

app:
  kafka:
    topics:
      user-onboarding: ${KAFKA_TOPIC_USER_ONBOARDING:user-onboarding-topic}