server:
  port: ${IDENTITY_SERVICE_PORT:0}

# Cấu hình kết nối sang Keycloak Server dành cho Keycloak Admin Client
keycloak:
  server-url: ${KEYCLOAK_SERVER_URL:http://localhost:8180}
  realm: ${KEYCLOAK_REALM:food-delivery}
  admin-realm: ${KEYCLOAK_ADMIN_REALM:master}
  admin-client-id: ${KEYCLOAK_ADMIN_CLIENT_ID:admin-cli}
  admin-username: ${KEYCLOAK_ADMIN_USER:admin}
  admin-password: ${KEYCLOAK_ADMIN_PASSWORD:admin}
  client-id: ${KEYCLOAK_IDENTITY_SERVICE_CLIENT_ID:identity-service-client}
  client-secret: ${KEYCLOAK_IDENTITY_SERVICE_CLIENT_SECRET:identity-service-secret}

spring:
  kafka:
    bootstrap-servers: ${KAFKA_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  cloud:
    openfeign:
      client:
        config:
          default:
            loggerLevel: full
            connectTimeout: 2000 # 2 giây để kết nối mạng
            readTimeout: 5000    # 5 giây để chờ xử lý xong dữ liệu
          keycloak-auth-client:
            url: ${KEYCLOAK_SERVER_URL:http://localhost:8180}
            connectTimeout: 1000
            readTimeout: 3000
logging:
  level:
    feign: DEBUG

springdoc:
  api-docs:
    path: /api/v1/auth/v3/api-docs
  swagger-ui:
    enabled: false

app:
  kafka:
    topics:
      user-onboarding: ${KAFKA_TOPIC_USER_ONBOARDING:user-onboarding-topic}
  keycloak:
    frontend-redirect-uri: ${KEYCLOAK_REDIRECT_URI:http://localhost:5000/auth/callback}
    redirect-server-url: ${KEYCLOAK_REDIRECT_SERVER_URL:http://localhost:8180}

security:
  permit-all-paths:
    - "/api/v1/auth/**"