server:
  port: ${IDENTITY_SERVICE_PORT:8085}

# Cấu hình kết nối sang Keycloak Server dành cho Keycloak Admin Client
keycloak:
  server-url: ${KEYCLOAK_SERVER_URL:http://localhost:8180}
  realm: ${KEYCLOAK_REALM:food-delivery}
  admin-realm: ${KEYCLOAK_ADMIN_REALM:master}
  admin-client-id: ${KEYCLOAK_ADMIN_CLIENT_ID:admin-cli}
  admin-username: ${KEYCLOAK_ADMIN_USER:admin}
  admin-password: ${KEYCLOAK_ADMIN_PASSWORD:admin}

spring:
  kafka:
    bootstrap-servers: ${KAFKA_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer