server: # Cấu hình các thông số liên quan đến môi trường chạy của máy chủ nhúng (Embedded Server)
  # Tách cổng chạy của Config Server ra biến CONFIG_SERVER_PORT, mặc định là 8888
  port: ${CONFIG_SERVER_PORT:8888}

spring: # Cấu hình các thành phần lõi thuộc hệ sinh thái của framework Spring
  application:
    name: config-server
  profiles:
    # Tách chế độ chạy ra biến CONFIG_SERVER_PROFILE, mặc định là native để đọc file local
    active: ${CONFIG_SERVER_PROFILE:native}
  cloud: # Cấu hình các tính năng dành cho mô hình hệ thống phân tán (Microservices) của Spring Cloud
    config:
      server:
        native:
          # ĐƯỜNG DẪN ĐỘNG: Ghép từ biến gốc dự án ${CONFIG_REPO_ROOT} và tên thư mục chứa cấu hình ${CONFIG_REPO_DIR}
          search-locations: ${SPRING_CLOUD_CONFIG_SERVER_NATIVE_SEARCH_LOCATIONS:file:./food-delivery-backend/config-repo/}
